Create Článek “geolokační-data-mobilních-operátorů-principy-příklady-otázky”
opendata-mvcr/opendata-mvcr.github.io pull request #113
Opened 2020-10-08 19:47 UTC by dvoriik

Automatically generated by Netlify CMS

2020-10-09 05:13 UTC, jakubklimek commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
> +[ˇ1]: T-Mobile cca 40 %, O2 cca 40 %, Vodafone cca 20 %
@dvoriik Tyhle poznámky pod čarou nejsou dle metodiky. Obsahují informace, které by měly být normálně v textu. Čtenář neví, co v poznámce je, tak se nemůže rozhodnout, zda si ji přečte nebo ne.

2020-10-09 11:13 UTC, dvoriik commented
@jakubklimek upraveno - přidáno normálně do textu

2020-10-13 05:39 UTC, jakubklimek requested changes

2020-10-13 05:39 UTC, jakubklimek commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
> +[Český statistický úřad](https://www.czso.cz/ "Český statistický úřad") standardně zjišťuje dojížďku a vyjížďku do zaměstnání a škol - tato data však zjišťuje pouze 1x za 10 let při [Sčítání lidu, do
@dvoriik Odkazy nejsou dle metodiky, tedy stylem ze seznam odkazu je ve spodku dokumentu a tady se na ne jen odkazuje.

2020-10-13 05:39 UTC, jakubklimek commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
> +![](https://lh5.googleusercontent.com/bC4od_lLuXDxvKwwiaHmvu90H84VsqISV8G4ln1xl8LHio-UWPu4jEPLJHI7YENfgjvq3VisQoOhz8lxNTFNPbfX9vHFdt7phNtx1ML8iomCx38bqwhbQ8652OhMZ2CzUbRVVBdA)
Obrázky je třeba dát přímo k článku, ne jako odkazy pryč.

2020-10-13 05:39 UTC, jakubklimek commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
> +Jako podklad použijeme dataset [Pohyb obyvatel na základě dat mobilního operátora](https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2Fhttps---kod.brno.cz-
Za 'day' chybí mezera

2020-10-13 05:39 UTC, jakubklimek commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
> +![](https://lh4.googleusercontent.com/9yPlLha5xMtN9KI_wqENXPGTjmOFNTUugC6oNzQZbQiPxuzq5R0db_sIRyJ-MZf0EnVyTmJCO-jPsGG_OcqoFFNry8FPUVBaYsJGWVdUe0wkCd34SXDWZwy-TEXje0LsbOtkudEf)
Obrázky dle metodiky mají být vloženy jinak, a s popiskem.

2020-10-13 05:39 UTC, jakubklimek commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
> +0,1,1,610208,1,610208,2.55
Tohle by měla být [tabulka](https://www.markdownguide.org/extended-syntax/#tables)

2020-10-13 17:04 UTC, dvoriik commented
@jakubklimek zapracoval sem změny, tak to prosím čekni

2020-10-14 05:12 UTC, jakubklimek commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
> +506699,weekend,4,333
@dvoriik tady by to nemela byt tabulka?

2020-10-14 05:19 UTC, jakubklimek requested changes
@dvoriik Obrázky teď nejsou součástí pull requestu. Nezapomněl jsi je commitnout?

Důležitější otázka - viděl jsi ten svůj článek v jekyllu? Tipuji že ne...

2020-10-14 05:19 UTC, jakubklimek commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
> +* Článek se zaměřuje na podstatu fungování geolokačních dat mobilních operátorů s cílem přiblížit tato data veřejnosti a nastínit možnosti vlastní analýzy, včetně praktické ukázky. Zároveň bude cílem
Tady je z nějakého důvodu teďka položka seznamu:
![image](https://user-images.githubusercontent.com/718827/95946595-2a1ebd80-0ded-11eb-98cc-d280074f6f5c.png)

2020-10-15 10:37 UTC, MichalMed reviewed
Kapitola "výstupy" - upřesni, že se jedná o výstupy z kalibrace dat, takhle je to strašně matoucí. Taky bych předtím lépe popsal tu kalibraci, co to vlastně je a proč se to dělá. Takhle to vypadá, že tam něco vstupuje a konec, další kapitola. Na začátku kaitoly výstupy zmiňuješ typy analýzy, které ale nikde definovány ani zmíněny nejsou.

řádek 69 - viz tab ->viz tabulku.

Katalogizace v NKOD - máme se tím tedy v rámci článků vůbec zabývat, když nejde o open data? :-P Kromě prvního odstavce se sekce netýká katalogizace, spíše je to potenciál využití dat nebo relevantní use casy. Možná propojit tematicky s poslední sekcí, kam to spíš tematicky patří.

2020-10-15 10:37 UTC, MichalMed commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
> +[Český statistický úřad](https://www.czso.cz/ "Český statistický úřad") standardně zjišťuje dojížďku a vyjížďku do zaměstnání a škol - tato data však zjišťuje pouze 1x za 10 let při [Sčítání lidu, do
origin-destination -> požná vysvětlit pro českého čtenáře

2020-10-15 10:37 UTC, MichalMed commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
>  Jedná se o signalizační data, které vysílá SIM karta, prostřednictvím které se SIM připojuje do systému pozemních přenosových antén, tzv. síť BTS (basic transmitter stations). Každá anténa je schopna
... které vysílá SIM karta a jejichž prostřednictvím se připojuje do systému pozemních ...

2020-10-15 10:37 UTC, MichalMed commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
>  {% include image.html url="../attachments/články/geolokační-data-mobilních-operátorů-principy-příklady-otázky/obrázky/1.GSM.png" description="BTS od T-Mobile v Brně" %}
jestli tady měl být obrázek, tak ho nevidím

2020-10-15 10:37 UTC, MichalMed commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
> +Výsledek [Přítomné obyvatelstvo v obcích JMK](http://jmk.brno.ml/ "Přítomné ob. v JMK")  v programu [Carto](https://carto.com/ "Carto"). Zdrojový kód stránky je možné nalézt na [Gitlabu](https://bitb
první věta nemá přísudek

2020-10-15 10:37 UTC, MichalMed commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
>  Na základě těchto dat pak lze s určitou mírou (ne)přesnosti vizualizovat časoprostorové rytmy v obcích. Na základě příkladu výše tak máme rámcový přehled o vývoji počtu přítomných obyvatel v 672 obcí
co je to časoprostorový rytmus?
JMK - rozepiš co to je

2020-10-15 10:37 UTC, MichalMed commented on _clanky/geolokační-data-mobilních-operátorů-principy-příklady-otázky.md
> +V této ukázce budou vizualizovány základní přepravní proudy ve městě Brně prostřednictvím open-source geografického nástroje [QGIS](https://qgis.org/ "QGIS"). Cílem bude zobrazit hlavní přepravní pro
open source bych napsal bez pomlčky
co je to katastrální vazba? není to spíš vazba mezi KÚ?

2020-10-29 07:50 UTC, jakubklimek approved these changes

2020-10-29 14:25 UTC, merged