Článěk Znalostní grafy 3 - SPARQL
opendata-mvcr/opendata-mvcr.github.io pull request #123
Opened 2020-12-18 17:21 UTC by martinnec

2020-12-21 07:20 UTC, jakubklimek requested changes
1. V místech, kde se dotaz rozšiřuje o další predikáty (např tam, kde nám nestačí IRI poskytovatele, ale chceme jeho název), je třeba vysvětlit, kde vývojář vezme ten další predikát. To bývá nejčastější výtka vývojářů vůči SPARQL, že "neví, co tam psát".  V druhé části jsou nějaké základní explorační dotazy, ale to je pozdě, a je to složité. Představoval bych si něco jako link na konkrétní IRI - vede do browseru - tam je vidět, co za predikát je použito - ten použiju.
2. "zafixujeme" bych asi nahradil specifikujeme, nebo něčím méně hovorovým
3. Odkázal bych na Yasgui - jako lepší UI použitelné s libovolným endpointem a zvážil, zda příklady nelinkovat přímo na něj - tam se pro endpoint + dotaz dá vytvořit permalink.

2021-01-07 11:35 UTC, martinnec commented
Zapracoval jsem připomínky @jakubklimek

2021-01-08 06:59 UTC, jakubklimek requested changes
1. Chybí úvodní obrázek /attachments/články/znalostní-grafy/znalostní-grafy-03.jpg
2. Podle aktualizované metodiky by pro bitmapové obrázky místo jpg a png mělo být použito webp se ztrátovou resp. bezeztrátovou kompresí
3. V sekci o jišťování stuktury schématu mi trochu chybí připomenutí toho, že pokud datový zdroj umožňuje dereferenci IRI a browsení, tak to bývá jednodušší na zjištění struktury než dotazování SPARQLem. Je to sice napsáno cca v půlce článku, jenže tím že je článek dlouhý, to čtenář když se dostane až dolu už nemusí vědět.

2021-01-12 14:24 UTC, martinnec commented
Zapracoval jsem připomínky @jakubklimek

1. Udělal jsem nový úvodní webp obrázek. Měli jsme ale k předchozím dílům ten modrý šikmý pruh a to kreslit nebudu. Udělal jsem verzi bez pruhu pro všechny díly.
2. V těle článku mám  jen SVG, myslel si úvodní?
3. Úplně nesouhlasím, že je to jednodušší, ale text jsem upravil - tak, že SPARQL je nutný zjišťování schématu, pokud chci úplné schéma.

2021-01-12 14:46 UTC, jakubklimek approved these changes

2021-01-25 13:48 UTC, martinnec commented
@marievitova zapracoval jsem všechny připomínky z Google Docu na Github, je to ready na merge.

2021-01-25 15:22 UTC, merged