Data50 links repair
opendata-mvcr/opendata-mvcr.github.io pull request #255
Opened 2021-11-16 13:10 UTC by MichalMed

Opraveny linky do data50 a data200 po změně v lastníka v NKOD

2021-11-18 12:59 UTC, jakubklimek requested changes
Jak jsem psal na slacku, ty datumy a časy zveřejnění musí zůstat jak byly - cílem není články zařadit zase na začátek.
U části 2 a 3 pak vidim pouze nějaké nepodstatné změny konců řádek

2021-11-19 11:13 UTC, MichalMed commented
datumy jsem vrátil, konce řádek jsou nepodstatné

2021-11-19 11:52 UTC, jakubklimek commented
@MichalMed no já nevim, já pořád v https://github.com/opendata-mvcr/opendata-mvcr.github.io/pull/255/files vidim změny datumů

2021-11-19 13:37 UTC, MichalMed commented
Ten nový commit je přepisuje na ty původní. Kdybych revertnul celý commit, tak budu muset zase poslat další s těmi zmenami odkazů na nkod

2021-11-19 13:43 UTC, jakubklimek commented
No to právě nedělá, protože to by ten Pull Request jako celek neukazoval změnu. Např:
Před PR: https://github.com/opendata-mvcr/opendata-mvcr.github.io/pull/255/commits/e3c0058ff9ba7ed49bb1ae98f051dc9ab9b3a1c9#diff-72ca97f68c11e7dcc688a8f4cb7e4732e57c7ae91013ab265701f1101bd9c412L9
Aktuálně: https://github.com/opendata-mvcr/opendata-mvcr.github.io/pull/255/files#diff-72ca97f68c11e7dcc688a8f4cb7e4732e57c7ae91013ab265701f1101bd9c412L9

2021-11-19 14:23 UTC, MichalMed commented
:man_facepalming: už to vidím. Druhá a třetí část byly postlý o měsíc později

2021-11-19 16:08 UTC, merged